nodeLinker: node-modules

plugins:
  - checksum: a3051c22ae7bb88ce6ec0c7c9ac69b268a3f3a512cd2160dcbb7e7bc73a8b1b2c66e4544866a975975c545c33638fa82b3ab09f46f0e28b5e2cb51cf71c3a78a
    path: .yarn/plugins/plugin-duplicates-list.cjs
    spec: .yarn/plugins/plugin-duplicates-list.cjs

yarnPath: .yarn/releases/yarn-4.12.0.cjs
